export type BlogParagraphBlock = {
    type: "paragraph";
    text: string;
};

export type BlogHeadingBlock = {
    type: "heading";
    level: 2 | 3 | 4;
    text: string;
};

export type BlogImageBlock = {
    type: "image";
    src: string;
    alt: string;
    caption?: string;
};

export type BlogCodeBlock = {
    type: "code";
    language: string;
    code: string;
    caption?: string;
};

export type BlogBlock =
    | BlogParagraphBlock
    | BlogHeadingBlock
    | BlogImageBlock
    | BlogCodeBlock;

export type BlogPost = {
    slug: string;
    title: string;
    summary: string;
    publishedAt: string;
    heroImage?: string;
    tags?: string[];
    blocks: BlogBlock[];
};

export const blogPosts: BlogPost[] = [
    {
        slug: "site-blog-launch",
        title: "Adding a Blog to This Site",
        summary:
            "A first pass at a flexible block-based blog system for text and images.",
        publishedAt: "2026-02-16",
        heroImage: "/img/blog/site-blog-launch/system-overview.png",
        tags: ["site", "engineering"],
        blocks: [
            {
                type: "paragraph",
                text: "This blog is generated by the same static build pipeline as the rest of the site, so publishing stays simple and local-first.",
            },
            {
                type: "heading",
                level: 2,
                text: "Why blocks",
            },
            {
                type: "paragraph",
                text: "Posts are composed from ordered content blocks, which means there is no fixed limit on sections, images, or text chunks.",
            },
            {
                type: "image",
                src: "/img/blog/site-blog-launch/system-overview.png",
                alt: "A sample preview image used by the first blog post.",
                caption: "Seed image for the blog system.",
            },
            {
                type: "heading",
                level: 2,
                text: "TypeScript snippet",
            },
            {
                type: "code",
                language: "ts",
                caption: "Blog code block schema (minimal example).",
                code: `type BlogCodeBlock = {
    type: "code";
    language: string;
    code: string;
    caption?: string;
};`,
            },
        ],
    },
];
